Fix the remaining `DepcrecationWarning` for `datetime.datetime.utcnow` on Python 3.12.
